name: Manual Windows Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'windows'
        type: choice
        options:
        - windows
        - windows-debug

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        
    - name: Install PyInstaller
      run: |
        pip install pyinstaller==6.15.0
        
    - name: Build Windows application
      run: |
        pyinstaller --onefile --console --name=GoogleDriveDownloaderWeb --add-data=README.md:. --add-data=USAGE_GUIDE.md:. --add-data=依頼.py:. --exclude-module=backports --exclude-module=jaraco --exclude-module=pkg_resources --exclude-module=tkinter --exclude-module=matplotlib --exclude-module=numpy simple_gui.py
        
    - name: Create Windows package
      run: |
        if exist "GoogleDriveDownloaderWeb_Package_Windows" (
          rmdir /s /q "GoogleDriveDownloaderWeb_Package_Windows"
        )
        mkdir "GoogleDriveDownloaderWeb_Package_Windows"
        copy "dist\GoogleDriveDownloaderWeb.exe" "GoogleDriveDownloaderWeb_Package_Windows\"
        copy "client_secret.json" "GoogleDriveDownloaderWeb_Package_Windows\"
        copy "依頼.py" "GoogleDriveDownloaderWeb_Package_Windows\"
        copy "README.md" "GoogleDriveDownloaderWeb_Package_Windows\"
        copy "USAGE_GUIDE.md" "GoogleDriveDownloaderWeb_Package_Windows\"
        copy "README_WINDOWS.md" "GoogleDriveDownloaderWeb_Package_Windows\"
        
        echo @echo off > "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo Google Drive Image Downloader Web Version Starting... >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo. >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo Browser will open automatically. If not, manually access http://localhost:8080 >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo. >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo To stop the application, close this window. >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo echo. >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo pause >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo GoogleDriveDownloaderWeb.exe >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        echo pause >> "GoogleDriveDownloaderWeb_Package_Windows\start_application.bat"
        
    - name: Create ZIP artifact
      run: |
        powershell Compress-Archive -Path "GoogleDriveDownloaderWeb_Package_Windows" -DestinationPath "GoogleDriveDownloaderWeb_Package_Windows.zip"
        
    - name: Upload Windows package
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Package-${{ github.run_number }}
        path: GoogleDriveDownloaderWeb_Package_Windows.zip
        retention-days: 30 